#Use the new container-based infrastructure
sudo: false
language: sourcepawn

#Install some apt packages needed for spcomp
addons:
  apt_packages:
    - lib32stdc++6
    
matrix:
  allow_failures:
    - env: SOURCEMODVERSION=1.8.0-git6050
    - env: SOURCEMODURL=https://sm.alliedmods.net/smdrop/1.8/sourcemod-1.8.0-git6050-linux.tar.gz
    
#Set the build environment
env:
  - SOURCEMODURL=https://sm.alliedmods.net/smdrop/1.8/sourcemod-1.8.0-git6050-linux.tar.gz
  - SOURCEMODURL=https://sm.alliedmods.net/smdrop/1.9/sourcemod-1.9.0-git6282-linux.tar.gz
  - SOURCEMODURL=https://sm.alliedmods.net/smdrop/1.10/sourcemod-1.10.0-git6501-linux.tar.gz
  - SOURCEMODVERSION=1.8.0-git6050
  - SOURCEMODVERSION=1.9.0-git6282
  - SOURCEMODVERSION=1.10.0-git6501

#And compile!
before_script:
  - wget "$SOURCEMODURL" -O game/sourcemod-$SOURCEMODVERSION-linux.tar.gz
  - cd game
  - tar -xzf sourcemod-$SOURCEMODVERSION-linux.tar.gz
  - cd addons/sourcemod/scripting/
  - wget https://raw.githubusercontent.com/drhax9908/smupdater-godtony/master/scripting/include/updater.inc -O include/updater.inc
  - chmod +x spcomp

script:
  - ./compile.sh sbpp_main.sp sbpp_admcfg.sp sbpp_comms.sp sbpp_checker.sp sbpp_sleuth.sp sbpp_report.sp
